# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_generate.server2_pb2 as server2__pb2


class Server2Stub(object):
    """服务端接口类
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fun2 = channel.unary_unary(
                '/proto.Server2/fun2',
                request_serializer=server2__pb2.Fun2Request.SerializeToString,
                response_deserializer=server2__pb2.Fun2Reply.FromString,
                )


class Server2Servicer(object):
    """服务端接口类
    """

    def fun2(self, request, context):
        """服务端接口方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Server2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fun2': grpc.unary_unary_rpc_method_handler(
                    servicer.fun2,
                    request_deserializer=server2__pb2.Fun2Request.FromString,
                    response_serializer=server2__pb2.Fun2Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Server2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server2(object):
    """服务端接口类
    """

    @staticmethod
    def fun2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Server2/fun2',
            server2__pb2.Fun2Request.SerializeToString,
            server2__pb2.Fun2Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
