# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server2.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\021com.q49a.grpc.w2mB\014Server2ProtoP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rserver2.proto\x12\x05proto\",\n\x0b\x46un2Request\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\"\x1c\n\tFun2Reply\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x07Server2\x12.\n\x04\x66un2\x12\x12.proto.Fun2Request\x1a\x10.proto.Fun2Reply\"\x00\x42#\n\x11\x63om.q49a.grpc.w2mB\x0cServer2ProtoP\x00\x62\x06proto3'
)




_FUN2REQUEST = _descriptor.Descriptor(
  name='Fun2Request',
  full_name='proto.Fun2Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='proto.Fun2Request.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='proto.Fun2Request.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_FUN2REPLY = _descriptor.Descriptor(
  name='Fun2Reply',
  full_name='proto.Fun2Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.Fun2Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Fun2Request'] = _FUN2REQUEST
DESCRIPTOR.message_types_by_name['Fun2Reply'] = _FUN2REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fun2Request = _reflection.GeneratedProtocolMessageType('Fun2Request', (_message.Message,), {
  'DESCRIPTOR' : _FUN2REQUEST,
  '__module__' : 'server2_pb2'
  # @@protoc_insertion_point(class_scope:proto.Fun2Request)
  })
_sym_db.RegisterMessage(Fun2Request)

Fun2Reply = _reflection.GeneratedProtocolMessageType('Fun2Reply', (_message.Message,), {
  'DESCRIPTOR' : _FUN2REPLY,
  '__module__' : 'server2_pb2'
  # @@protoc_insertion_point(class_scope:proto.Fun2Reply)
  })
_sym_db.RegisterMessage(Fun2Reply)


DESCRIPTOR._options = None

_SERVER2 = _descriptor.ServiceDescriptor(
  name='Server2',
  full_name='proto.Server2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='fun2',
    full_name='proto.Server2.fun2',
    index=0,
    containing_service=None,
    input_type=_FUN2REQUEST,
    output_type=_FUN2REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER2)

DESCRIPTOR.services_by_name['Server2'] = _SERVER2

# @@protoc_insertion_point(module_scope)
