# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server1.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\021com.q49a.grpc.w2mB\014Server1ProtoP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rserver1.proto\x12\x05proto\",\n\x0b\x46un1Request\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\"\x1c\n\tFun1Reply\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x07Server1\x12.\n\x04\x66un1\x12\x12.proto.Fun1Request\x1a\x10.proto.Fun1Reply\"\x00\x42#\n\x11\x63om.q49a.grpc.w2mB\x0cServer1ProtoP\x00\x62\x06proto3'
)




_FUN1REQUEST = _descriptor.Descriptor(
  name='Fun1Request',
  full_name='proto.Fun1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='proto.Fun1Request.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='proto.Fun1Request.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_FUN1REPLY = _descriptor.Descriptor(
  name='Fun1Reply',
  full_name='proto.Fun1Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.Fun1Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Fun1Request'] = _FUN1REQUEST
DESCRIPTOR.message_types_by_name['Fun1Reply'] = _FUN1REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fun1Request = _reflection.GeneratedProtocolMessageType('Fun1Request', (_message.Message,), {
  'DESCRIPTOR' : _FUN1REQUEST,
  '__module__' : 'server1_pb2'
  # @@protoc_insertion_point(class_scope:proto.Fun1Request)
  })
_sym_db.RegisterMessage(Fun1Request)

Fun1Reply = _reflection.GeneratedProtocolMessageType('Fun1Reply', (_message.Message,), {
  'DESCRIPTOR' : _FUN1REPLY,
  '__module__' : 'server1_pb2'
  # @@protoc_insertion_point(class_scope:proto.Fun1Reply)
  })
_sym_db.RegisterMessage(Fun1Reply)


DESCRIPTOR._options = None

_SERVER1 = _descriptor.ServiceDescriptor(
  name='Server1',
  full_name='proto.Server1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='fun1',
    full_name='proto.Server1.fun1',
    index=0,
    containing_service=None,
    input_type=_FUN1REQUEST,
    output_type=_FUN1REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER1)

DESCRIPTOR.services_by_name['Server1'] = _SERVER1

# @@protoc_insertion_point(module_scope)
