# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasklog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasklog.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\027com.q49a.grpc.w2m.protoB\014TaskLogProtoP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtasklog.proto\x12\x05proto\"-\n\nLogRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x08LogReply\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x07TaskLog\x12\x32\n\ncollectLog\x12\x11.proto.LogRequest\x1a\x0f.proto.LogReply\"\x00\x42)\n\x17\x63om.q49a.grpc.w2m.protoB\x0cTaskLogProtoP\x00\x62\x06proto3'
)




_LOGREQUEST = _descriptor.Descriptor(
  name='LogRequest',
  full_name='proto.LogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='proto.LogRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.LogRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=69,
)


_LOGREPLY = _descriptor.Descriptor(
  name='LogReply',
  full_name='proto.LogReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.LogReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['LogRequest'] = _LOGREQUEST
DESCRIPTOR.message_types_by_name['LogReply'] = _LOGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGREQUEST,
  '__module__' : 'tasklog_pb2'
  # @@protoc_insertion_point(class_scope:proto.LogRequest)
  })
_sym_db.RegisterMessage(LogRequest)

LogReply = _reflection.GeneratedProtocolMessageType('LogReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGREPLY,
  '__module__' : 'tasklog_pb2'
  # @@protoc_insertion_point(class_scope:proto.LogReply)
  })
_sym_db.RegisterMessage(LogReply)


DESCRIPTOR._options = None

_TASKLOG = _descriptor.ServiceDescriptor(
  name='TaskLog',
  full_name='proto.TaskLog',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='collectLog',
    full_name='proto.TaskLog.collectLog',
    index=0,
    containing_service=None,
    input_type=_LOGREQUEST,
    output_type=_LOGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKLOG)

DESCRIPTOR.services_by_name['TaskLog'] = _TASKLOG

# @@protoc_insertion_point(module_scope)
