# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_generate.tasklog_pb2 as tasklog__pb2


class TaskLogStub(object):
    """服务端接口类
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.collectLog = channel.unary_unary(
                '/proto.TaskLog/collectLog',
                request_serializer=tasklog__pb2.LogRequest.SerializeToString,
                response_deserializer=tasklog__pb2.LogReply.FromString,
                )


class TaskLogServicer(object):
    """服务端接口类
    """

    def collectLog(self, request, context):
        """服务端接口方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskLogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'collectLog': grpc.unary_unary_rpc_method_handler(
                    servicer.collectLog,
                    request_deserializer=tasklog__pb2.LogRequest.FromString,
                    response_serializer=tasklog__pb2.LogReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TaskLog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskLog(object):
    """服务端接口类
    """

    @staticmethod
    def collectLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.TaskLog/collectLog',
            tasklog__pb2.LogRequest.SerializeToString,
            tasklog__pb2.LogReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
