# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_generate.taskmanage_pb2 as taskmanage__pb2


class TaskManageStub(object):
    """服务端接口类
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listActiveTask = channel.unary_unary(
                '/proto.TaskManage/listActiveTask',
                request_serializer=taskmanage__pb2.ListActiveRequest.SerializeToString,
                response_deserializer=taskmanage__pb2.ListActiveReply.FromString,
                )
        self.killTask = channel.unary_unary(
                '/proto.TaskManage/killTask',
                request_serializer=taskmanage__pb2.KillRequest.SerializeToString,
                response_deserializer=taskmanage__pb2.KillReply.FromString,
                )


class TaskManageServicer(object):
    """服务端接口类
    """

    def listActiveTask(self, request, context):
        """服务端接口方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def killTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listActiveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.listActiveTask,
                    request_deserializer=taskmanage__pb2.ListActiveRequest.FromString,
                    response_serializer=taskmanage__pb2.ListActiveReply.SerializeToString,
            ),
            'killTask': grpc.unary_unary_rpc_method_handler(
                    servicer.killTask,
                    request_deserializer=taskmanage__pb2.KillRequest.FromString,
                    response_serializer=taskmanage__pb2.KillReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TaskManage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskManage(object):
    """服务端接口类
    """

    @staticmethod
    def listActiveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.TaskManage/listActiveTask',
            taskmanage__pb2.ListActiveRequest.SerializeToString,
            taskmanage__pb2.ListActiveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def killTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.TaskManage/killTask',
            taskmanage__pb2.KillRequest.SerializeToString,
            taskmanage__pb2.KillReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
