# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskmanage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='taskmanage.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\027com.q49a.grpc.w2m.protoB\017TaskManageProtoP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10taskmanage.proto\x12\x05proto\"\x13\n\x11ListActiveRequest\" \n\x0fListActiveReply\x12\r\n\x05tasks\x18\x01 \x03(\t\"\x1d\n\x0bKillRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\"\x1c\n\tKillReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x01\n\nTaskManage\x12\x44\n\x0elistActiveTask\x12\x18.proto.ListActiveRequest\x1a\x16.proto.ListActiveReply\"\x00\x12\x32\n\x08killTask\x12\x12.proto.KillRequest\x1a\x10.proto.KillReply\"\x00\x42,\n\x17\x63om.q49a.grpc.w2m.protoB\x0fTaskManageProtoP\x00\x62\x06proto3'
)




_LISTACTIVEREQUEST = _descriptor.Descriptor(
  name='ListActiveRequest',
  full_name='proto.ListActiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=46,
)


_LISTACTIVEREPLY = _descriptor.Descriptor(
  name='ListActiveReply',
  full_name='proto.ListActiveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tasks', full_name='proto.ListActiveReply.tasks', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=80,
)


_KILLREQUEST = _descriptor.Descriptor(
  name='KillRequest',
  full_name='proto.KillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='proto.KillRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=111,
)


_KILLREPLY = _descriptor.Descriptor(
  name='KillReply',
  full_name='proto.KillReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.KillReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['ListActiveRequest'] = _LISTACTIVEREQUEST
DESCRIPTOR.message_types_by_name['ListActiveReply'] = _LISTACTIVEREPLY
DESCRIPTOR.message_types_by_name['KillRequest'] = _KILLREQUEST
DESCRIPTOR.message_types_by_name['KillReply'] = _KILLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListActiveRequest = _reflection.GeneratedProtocolMessageType('ListActiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTACTIVEREQUEST,
  '__module__' : 'taskmanage_pb2'
  # @@protoc_insertion_point(class_scope:proto.ListActiveRequest)
  })
_sym_db.RegisterMessage(ListActiveRequest)

ListActiveReply = _reflection.GeneratedProtocolMessageType('ListActiveReply', (_message.Message,), {
  'DESCRIPTOR' : _LISTACTIVEREPLY,
  '__module__' : 'taskmanage_pb2'
  # @@protoc_insertion_point(class_scope:proto.ListActiveReply)
  })
_sym_db.RegisterMessage(ListActiveReply)

KillRequest = _reflection.GeneratedProtocolMessageType('KillRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLREQUEST,
  '__module__' : 'taskmanage_pb2'
  # @@protoc_insertion_point(class_scope:proto.KillRequest)
  })
_sym_db.RegisterMessage(KillRequest)

KillReply = _reflection.GeneratedProtocolMessageType('KillReply', (_message.Message,), {
  'DESCRIPTOR' : _KILLREPLY,
  '__module__' : 'taskmanage_pb2'
  # @@protoc_insertion_point(class_scope:proto.KillReply)
  })
_sym_db.RegisterMessage(KillReply)


DESCRIPTOR._options = None

_TASKMANAGE = _descriptor.ServiceDescriptor(
  name='TaskManage',
  full_name='proto.TaskManage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='listActiveTask',
    full_name='proto.TaskManage.listActiveTask',
    index=0,
    containing_service=None,
    input_type=_LISTACTIVEREQUEST,
    output_type=_LISTACTIVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='killTask',
    full_name='proto.TaskManage.killTask',
    index=1,
    containing_service=None,
    input_type=_KILLREQUEST,
    output_type=_KILLREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKMANAGE)

DESCRIPTOR.services_by_name['TaskManage'] = _TASKMANAGE

# @@protoc_insertion_point(module_scope)
