# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskcrawler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='taskcrawler.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\027com.q49a.grpc.w2m.protoB\014Server1ProtoP\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11taskcrawler.proto\x12\x05proto\"3\n\x0f\x43rawler1Request\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08keywords\x18\x02 \x01(\t\" \n\rCrawler1Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0btaskcrawler\x12:\n\x08\x63rawler1\x12\x16.proto.Crawler1Request\x1a\x14.proto.Crawler1Reply\"\x00\x42)\n\x17\x63om.q49a.grpc.w2m.protoB\x0cServer1ProtoP\x00\x62\x06proto3'
)




_CRAWLER1REQUEST = _descriptor.Descriptor(
  name='Crawler1Request',
  full_name='proto.Crawler1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='proto.Crawler1Request.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keywords', full_name='proto.Crawler1Request.keywords', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=79,
)


_CRAWLER1REPLY = _descriptor.Descriptor(
  name='Crawler1Reply',
  full_name='proto.Crawler1Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.Crawler1Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Crawler1Request'] = _CRAWLER1REQUEST
DESCRIPTOR.message_types_by_name['Crawler1Reply'] = _CRAWLER1REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Crawler1Request = _reflection.GeneratedProtocolMessageType('Crawler1Request', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLER1REQUEST,
  '__module__' : 'taskcrawler_pb2'
  # @@protoc_insertion_point(class_scope:proto.Crawler1Request)
  })
_sym_db.RegisterMessage(Crawler1Request)

Crawler1Reply = _reflection.GeneratedProtocolMessageType('Crawler1Reply', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLER1REPLY,
  '__module__' : 'taskcrawler_pb2'
  # @@protoc_insertion_point(class_scope:proto.Crawler1Reply)
  })
_sym_db.RegisterMessage(Crawler1Reply)


DESCRIPTOR._options = None

_TASKCRAWLER = _descriptor.ServiceDescriptor(
  name='taskcrawler',
  full_name='proto.taskcrawler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=115,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='crawler1',
    full_name='proto.taskcrawler.crawler1',
    index=0,
    containing_service=None,
    input_type=_CRAWLER1REQUEST,
    output_type=_CRAWLER1REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKCRAWLER)

DESCRIPTOR.services_by_name['taskcrawler'] = _TASKCRAWLER

# @@protoc_insertion_point(module_scope)
